name: CI for Eleventy Starter with Sass support, PostCSS and PurgeCSS
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and Test
        steps:
            - uses: actions/checkout@v2
            - name: Cache pnpm modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-

            - name: Prepare pnpm for install
              uses: pnpm/action-setup@v2.1.0
              with:
                  version: 6.0.2
                  run_install: true
            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 16
            - run: |
                  npm run build
              name: Build and Test
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: '${{ secrets.GITHUB_TOKEN }}'
                  publish_dir: ./dist
